---
title: "Homework4"
author: "Guojing Wu | UNI: gw2383"
date: "11/23/2019"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1

### (a) As we know, we are able to examine whether testing treatment is significantly better than control in a non-inferiority trial without inflating the family-wide type I error rate.  So should we always take advantage of this “free lunch” and always use the non-inferiority design (as opposed to superiority design)?  Please justify your answer. 

Not always. Because when we need superiority design, but then switch to non-inferiority design, we need:

* The noninferiority margin with respect to the control treatment was predefined

* The trial was properly designed and carried out in accordance with the strict requirements of a noninferiority trial

* The sensitivity of the trial is high enough to ensure that it is capable of detecting relevant differences if they exist

* There is direct or indirect evidence that the control treatment is showing its usual level of efficacy

So not always.

### (b) After a non-inferiority clinical trial, a new therapy may be accepted as effective, even if its treatment effect is slightly smaller than the current standard. It is therefore possible that, after a series of trials where the new therapy is slightly worse than the preceding drugs, an ineffective or harmful therapy might be incorrectly declared efficacious; this is known as 'bio-creep'. What would you recommend the investigator to avoid bio-creep when designing a non-inferiority trial? 

They need a more careful choice of the margin in NI trials

### (c) In FDA’s guideline for non-inferiority trials, the majority of discussion was to quantify the treatment effect of active control.  Why this is so important? Please discuss what consequence we have to take if the treatment effect of active control compared to placebo (i.e., M1) is not properly specified (i.e., discuss the cases that the assumed value for M1 is too large or too small). 

When M1 is too small, the treatment effect for AC is not enough to ensure, when declare NI, treatment is better than placebo.

When M1 is too large, then it would leads to waste of time and money, and has no assay senstivity.

